# Copyright (c) 2023, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set setup_py_data = load_setup_py_data() %}

package:
  name: merlin-systems
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ git_revision_count }}
  noarch: python
  script: python -m pip install . -vvv

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    {% for req in setup_py_data.get('install_requires', []) %}
      # the treelite_runtime pip package is included in the treelite conda pacakge
      # and not available to install separately
      {% if not req.startswith("treelite_runtime") %}
    - {{ req }}
      {% endif %}
    {% endfor %}

about:
  home: https://github.com/NVIDIA-Merlin/systems
  license_file: LICENSE
  summary: Merlin Systems provides tools for combining recommendation models with other elements of production recommender systems (like feature stores, nearest neighbor search, and exploration strategies) into end-to-end recommendation pipelines that can be served with Triton Inference Server.
