name: "0_predictpytorch"
platform: "pytorch_libtorch"
input {
  name: "input"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
output {
  name: "OUTPUT__0"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
parameters {
  key: "INFERENCE_MODE"
  value {
    string_value: "true"
  }
}
backend: "pytorch"