name: fil

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools==59.4.0 wheel
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install xgboost lightgbm sklearn
          conda install cuml --channel rapidsai
      - name: Build
        run: |
          python setup.py develop
      - name: Run unittests
        run: |
          python -m pytest -rxs tests/unit/systems/fil/
