name: lint

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.0

      - name: Notify Failure in Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "message": "GitHub Action job failure on github.ref `${{ github.ref }}`",
              "pull_request": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "workflow": "${{ github.workflow }}",
              "logs_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          PR_NUMBER: ${{ github.event.number }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Failure in Slack
        id: slack2
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ success() && github.ref == 'refs/pull/346/merge' }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "message": "FROM PR GitHub Action job failure on github.ref `${{ github.ref }}`",
              "pull_request": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "workflow": "${{ github.workflow }}",
              "logs_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          PR_NUMBER: ${{ github.event.number }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
