name: GPU CI (Post-merge)

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  gpu-ci-postmerge:
    runs-on: 1GPU

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          ref_type=${{ github.ref_type }}
          branch=main
          if [[ $ref_type == "tag"* ]]
          then
            raw=$(git branch -r --contains ${{ github.ref_name }})
            branch=${raw/origin\/}
          fi
          cd ${{ github.workspace }}; tox -e test-gpu-postmerge -- $branch
