name: Send Slack Notification

# on:
#   workflow_run:
#     workflows: ["CPU CI", "lint"]
#     types: [completed]

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify in Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "key": "value",
              "id": "$PR_NUMBER",
              "event": "${{ github.event.workflow_run.event }}",
              "conclusion": "${{github.event.workflow_run.conclusion}}"
            }
        env:
          PR_NUMBER: ${{ github.event.number }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
